# Suno AI - Auto git push script
# Runs at 10:10 JST via Windows Task Scheduler (SunoLyricsPush)
# Commits and pushes lyrics files created by Cowork PM Agent (10:00 JST)

$repoPath = "$env:USERPROFILE\Documents\test\test"
$today    = (Get-Date).ToString("yyyy-MM-dd")
$lyricsFile = "$repoPath\lyrics\$today\song.txt"
$outputDir  = "$repoPath\output"
$logFile    = "$outputDir\push_log.txt"

if (-not (Test-Path $outputDir)) { New-Item -ItemType Directory -Path $outputDir | Out-Null }

function Write-Log($msg) {
    $ts   = (Get-Date).ToString("yyyy-MM-dd HH:mm:ss")
    $line = "$ts $msg"
    $line | Tee-Object -FilePath $logFile -Append
}

Write-Log "=== auto_push_lyrics.ps1 START (today=$today) ==="

if (-not (Test-Path $lyricsFile)) {
    Write-Log "ERROR: Lyrics file not found: $lyricsFile"
    exit 1
}

$content = Get-Content $lyricsFile -Raw -Encoding UTF8
if ($content -match "title: \[your title here\]" -or $content -match "PLACEHOLDER") {
    Write-Log "WARN: Placeholder still present. Lyrics generation may have failed."
    exit 1
}
Write-Log "OK: Lyrics file verified: $lyricsFile"

Set-Location $repoPath

# Remove stale lock files left by sandbox
$lockFiles = @("$repoPath\.git\index.lock", "$repoPath\.git\HEAD.lock")
foreach ($lf in $lockFiles) {
    if (Test-Path $lf) {
        Remove-Item $lf -Force -ErrorAction SilentlyContinue
        Write-Log "UNLOCK: removed $lf"
    }
}

$branch = (git rev-parse --abbrev-ref HEAD 2>&1)
Write-Log "Branch: $branch"

git config user.email "mossan72.tsubaki@gmail.com"
git config user.name "PM Agent"

# Day-of-week style
$dayOfWeek = (Get-Date).DayOfWeek.value__
$styleMap  = @{0="Hip-Hop"; 1="J-POP"; 2="Dance"; 3="Rock"; 4="Ballad"; 5="EDM"; 6="Anime"}
$style     = $styleMap[$dayOfWeek]

git restore --staged . 2>&1 | Out-Null
git add "lyrics\$today\song.txt" 2>&1 | Out-Null
Write-Log "git add done: lyrics\$today\song.txt"

$commitMsg    = "feat(lyrics): $today $style auto-generated by PM Agent"
$commitResult = (git commit -m $commitMsg 2>&1) -join "`n"
Write-Log "git commit: $commitResult"

$alreadyCommitted = $commitResult -match "nothing to commit" -or $commitResult -match "nothing added to commit" -or $commitResult -match "no changes added to commit"
if ($LASTEXITCODE -eq 0 -or $alreadyCommitted) {
    if ($alreadyCommitted) {
        Write-Log "INFO: Already committed - push only"
    }
    $pushResult = (git push origin HEAD 2>&1) -join "`n"
    Write-Log "git push: $pushResult"
    if ($LASTEXITCODE -eq 0) {
        Write-Log "SUCCESS: Lyrics pushed - GitHub Actions will start quality check"
    } else {
        Write-Log "WARN: push failed: $pushResult"
        exit 1
    }
} else {
    Write-Log "WARN: commit failed: $commitResult"
    exit 1
}

Write-Log "=== DONE ==="
